### PR TITLE
Normalize ADT in `assume`

### LINKED ISSUE #1096: ADT: Normalize representatives in assume
Following #1087 I believe the `assume_literals` function is incorrect: it should call `Uf.find_r` on all semantic values that appear in the literals.

Semantic values that appear in the literals given to `assume` are not guaranteed to be in normal form, even though they usually are: during CC(X) resolution I believe it is possible to generate a literal such as `x = y` then later pick a new representative for `y` or `x`. I have seen this happen with bit-vectors; presumably it can also happen with ADTs.

(Sorry, I missed it during review!)

### PR DESCRIPTION
**Pull request by Halbaroth**
Fix issue #1096

### CODE REVIEW

File: src/lib/reasoners/adt_rel.ml [hunk 1]
```diff
@@ -431,6 +431,8 @@ let assume_literals la uf env =
        match lit with
        | Eq (r1, r2) as l, _, ex, Th_util.Subst when is_adt r1 ->
          Debug.assume l;
+         let r1, _ = Uf.find_r uf r1 in
```
Comment (bclement-ocp) [inline src/lib/reasoners/adt_rel.ml]: This one looks wrong?

File: src/lib/reasoners/adt_rel.ml [hunk 2]
```diff
@@ -439,6 +441,8 @@ let assume_literals la uf env =
 
        | Distinct (false, [r1; r2]) as l, _, ex, _ when is_adt r2 ->
          Debug.assume l;
+         let r1, _ = Uf.find_r uf r1 in
+         let r2, _ = Uf.find_r uf r2 in
```
Comment (bclement-ocp) [inline src/lib/reasoners/adt_rel.ml]: The explanations should be added to `ex`

**Review by bclement-ocp — CHANGES_REQUESTED** [review]

File: src/lib/reasoners/adt_rel.ml (hunk 2 above)
Comment (Halbaroth) [reply src/lib/reasoners/adt_rel.ml]: Uhm, I wasn't sure it was necessary because the explanation may be added by a `subst` literal? I agree it's safer to add it.

File: src/lib/reasoners/adt_rel.ml (hunk 1 above)
Comment (Halbaroth) [reply src/lib/reasoners/adt_rel.ml]: Ok, I'm not sure to understand what's going on here. I didn't find a failure-induced input. I understood that CC(X) can send literals with new class representatives to the ADT theory before emitting a subst literal? Is it the problem?

Comment (bclement-ocp) [reply src/lib/reasoners/adt_rel.ml]: There can only be an `Eq (r1, r2)` with `Subst` origin if `r2` was the representative for `r1` at some point, so `Uf.find_r uf r1` and `Uf.find_r uf r2` should always be equal here, which makes `assume_subst` not very useful.

We need to call `Uf.find_r uf r2` to ensure the most up-to-date representative, although after checking in ccx.ml  and contrary to what I said at the meeting for `Subst` equalities that should not be needed either (they are added in `add_touched` immediately before calling `assume`, so they are guaranteed to be up-to-date).

File: src/lib/reasoners/adt_rel.ml (hunk 2 above)
Comment (bclement-ocp) [reply src/lib/reasoners/adt_rel.ml]: It is necessary. If `ex` justifies that `r1 <> r2`, `ex` on its own is not enough to justify `rr1 <> rr2`.

(For instance if we have `x <> y` and `x = x'` ; `y = y'`, `x <> y` alone is not sufficient to justify `x' <> y'` ; we need all 3 facts (`x <> y`, `x = x'` and `y = y'`) to derive `x' <> y'`)

File: src/lib/reasoners/adt_rel.ml (hunk 1 above)
Comment (bclement-ocp) [reply src/lib/reasoners/adt_rel.ml]: To clarify; nothing needs to be done *for `Subst` equalities specifically*.

File: src/lib/reasoners/adt_rel.ml (hunk 2 above)
Comment (bclement-ocp) [reply src/lib/reasoners/adt_rel.ml]: Note that there is no guarantee about the order in which we treat the literals (they are shuffled in `make_unique`).

File: src/lib/reasoners/adt_rel.ml [hunk 3]
```diff
@@ -439,18 +439,26 @@ let assume_literals la uf env =
...
-         let env = add_rec r1 uf env in
-         let env = add_rec r2 uf env in
-         assume_distinct ~ex r1 r2 env
+         let env = add_rec rr1 uf env in
+         let env = add_rec rr2 uf env in
+         assume_distinct ~ex rr1 rr2 env
 
        | Builtin (true, Sy.IsConstr c, [r]) as l, _, ex, _ ->
          Debug.assume l;
+         let r, _ = Uf.find_r uf r in
```
Comment (Halbaroth) [inline src/lib/reasoners/adt_rel.ml]: I guess I have to add the explanation of `find_r` to `ex`?

Comment (bclement-ocp) [reply src/lib/reasoners/adt_rel.ml]: I think so (here and in the `false` case below)

**Comment by Halbaroth** [comment]
I run a benchmark to be sure.

**Review by bclement-ocp — APPROVED** [review]
