### PR TITLE
Temporary fix of issue 744

### LINKED ISSUE #744: Crash on too long extraction
Alt-Ergo crashes on the following input:
```
(set-logic BV)
(declare-const x (_ BitVec 11))
(assert (= x ((_ extract 10 0) #b1010)))
(check-sat)
```
Output:
```
Fatal error: exception Invalid_argument("String.sub / Bytes.sub")
```
Command line:
```
$ alt-ergo --frontend dolmen test.smt2
```
I think the issue comes from the new canonizer in `bitv.ml`

### PR DESCRIPTION
**Pull request by Halbaroth**
This PR displays an appropriate error message when an ill-typed is produced by the Dolmen frontend.
The issue has been fixed on the master branch of Dolmen. Thus, this fix will be reverted when the next release of Dolmen will be released.

### CODE REVIEW

File: src/lib/frontend/d_cnf.ml [hunk 1]
```diff
@@ -1080,7 +1080,24 @@ let rec mk_expr
...
           (* Unary functions from FixedSizeBitVectors theory *)
-          | B.Bitv_extract { i; j; _ }, [ x ] -> E.BV.extract i j (mk x)
+          | B.Bitv_extract { i; j; _ }, [ x ] ->
+            let t = mk x in
+            let _ =
+              (* This temporary fix throws aways ill-typed expression produced
+                 by Dolmen 0.9. See issue
+                 https://github.com/Gbury/dolmen/issues/174.
+                 This code will be removed as soon as the next version of
+                 Dolmen has been released. *)
```
Comment (bclement-ocp) [inline src/lib/frontend/d_cnf.ml]: Please make an AE issue for this and reference it here.

**Review by bclement-ocp — CHANGES_REQUESTED** [review]

**Comment by Halbaroth** [comment]
Is it ok?

**Comment by bclement-ocp** [comment]
Plase add a link to #748 in the comment.

**Review by bclement-ocp — APPROVED** [review]
